### ISSUE TITLE
Support for custom domains via CNAME in quarto-publish

### ISSUE THREAD

**Issue by ns-rse** [quarto-dev/quarto-actions#118]
GitHub Pages supports [custom domains for GitHub pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site).

When using plain gh-pages this is set via _Settings > Pages > Custom domain_ but when publishing via a Custom GitHub Action this is ignored. As per item 4 under [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)

> If you are publishing your site with a custom GitHub Actions workflow, no CNAME file is created, so you need to create one manually (containing only a line of text with your custom domain).

If I manually add `CNAME` to the `gh-pages` branch it disappears the next time `quart-publish` runs as its not output by `quarto publish $TARGET ${{ inputs.path }} --no-browser`.

Having an option to include a `CNAME` argument which could be passed on would be useful, but I recognise that currently `quarto publish` has no way of using such an argument and work would also be needed on that side.

**Comment by cscheid** [comment]
Use the tools that Quarto provides for this sort of problem. In this case, add the `CNAME` file to the resources of your project, and it'll be published with it always.

## `_quarto.yml`

```yaml
project:
  type: website
  resources: 
    - "CNAME"
```

**Comment by ns-rse** [comment]
Thanks for the pointer @cscheid I wasn't aware of that option.
