### ISSUE TITLE
Quarto CLI not available

### ISSUE THREAD

**Issue by Robinlovelace** [quarto-dev/quarto-actions#120]
I've tried multiple times to get my pkgdown site built using pkgdown but to no avail: every time I've tried in the last few days it's failed with the following error message:

```
Error running quarto cli
```

And 

```
Error in `quarto::quarto_render()`:
✖ Error running quarto cli.
ℹ Rerun with `quiet = FALSE` to see the full error message.
Caused by error:
! System command 'quarto' failed
```

Source: https://github.com/acteng/netgen/actions/runs/12387364651/job/34576697088#step:7:84

I've checked and double checked my [pkgdown.yml](https://github.com/acteng/netgen/blob/main/.github/workflows/pkgdown.yaml) workflow file and even tried things like changing the OS version and `quarto` version installed, but nothing works. I've tried forking the `quarto-r` repo to reproduce the issue, as I'm using the same pkgdown.yml file as there, but the workflow is not being triggered for some reason.

Am I missing something? I'm sure Quarto *is* available but seems R cannot see it, is that a correct diagnosis?

Thanks,

Robin

**Comment by Robinlovelace** [comment]
Note: I can reproduce this locally so imagine it's something wrong with my config, maybe .Rbuildignore contents.

**Comment by cderv** [comment]
I don't think it is unavailable. Errors says that the quarto command fails. So something is failing when running `quarto render`. 

I don't think this is related to the quarto action. I think this is coming from pkgdown itself. 

It may be related to this 
- https://github.com/r-lib/pkgdown/issues/2830

And I am thinking maybe this is related to this issue 
- https://github.com/quarto-dev/quarto-r/issues/217

Though for the latter, a workaround is to make sure to install the package using `local::.` in `extra-packages` for example, under `r-lib/actions/setup-r-dependencies@v2` and you are already doing that. 

So could be a pkgdown issue in fact...

**Comment by Robinlovelace** [comment]
Weird in any case... .Rbuildignore could be a culprit do you think?

**Comment by cderv** [comment]
I am not sure. I wonder if this is a problem of configuration with `quarto_render()` that run `quarto render` in a new R background R process, and somehow the libpath is not having the package. 

In any case, **pkgdown** is hiding the real error. So we would need to reproduce locally with full quarto error to be sure the problem is what I think it is: the vignette is using the package and somehow it is not available to quarto process.

> I can reproduce this locally so imagine it's something wrong with my config, maybe .Rbuildignore contents.

I'll see if I can look into that with your project. Maybe pkgdown has an opt-in to be more verbose on the error.

**Comment by Robinlovelace** [comment]
Should we migrate this issue to pkgdown? Seems likely the best place.

**Comment by cderv** [comment]
> Should we migrate this issue to pkgdown? Seems likely the best place.

I do think this is the same as https://github.com/r-lib/pkgdown/issues/2830 so we would need to confirm if this is the same or not.

**Comment by Robinlovelace** [comment]
Closing for now, it remains a mystery, but don't see anything that can be done in the `quarto-actions` codebase to fix it.

**Comment by cderv** [comment]
This is the error 
````
processing file: schoolroutes.qmd
1/87                                 
2/87 [unnamed-chunk-1]               
3/87                                 
4/87 [unnamed-chunk-2]               
5/87                                 
6/87 [setup]                         
Error in `library()`:
! there is no package called 'netgen'
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 16. base::withRestarts(...)
 17. base (local) withRestartList(expr, restarts)
 18. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19. base (local) docall(restart$handler, restartArgs)
 21. evaluate (local) fun(base::quote(`<pckgNtFE>`))



Quitting from lines 62-63 [setup] (schoolroutes.qmd)
Execution halted
````

So this is indeed related to the way **pkgdown** install the package in a temp directory, which does not seem to be known by `quarto::quarto_render()` when running the background process.

**Comment by Robinlovelace** [comment]
OK well spotted.
