### ISSUE TITLE
Error linking shared objects/libraries when rendering blog post

### ISSUE THREAD

**Issue by PMassicotte** [quarto-dev/quarto-actions#38]
I am using `r-lib/actions/setup-renv@v2` to deploy a Quarto blog with `renv` [enabled](https://quarto.org/docs/projects/virtual-environments.html#using-renv). 

After examination of the rendering logs, I noticed that there were [errors concerning shared objects](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:6:79).

```shell
[ 7/16] posts/2022-08-11-how-to-read-amsr2-seaice-data/index.qmd
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/runner/work/_temp/renv/cache/v5/R-4.2/x86_64-pc-linux-gnu/terra/1.6-7/5d0f75086235149ccfa42c3f3596a079/terra/libs/terra.so':
  libproj.so.15: cannot open shared object file: No such file or directory
Calls: .main ... getNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```
This is likely because my system libraries are different from those on `ubuntu-latest`. Any advice on how I can tackle this problem?

Thank you,
Phil

**Comment by cscheid** [comment]
How are your system libraries interacting with the ones in GitHub Actions's? Did you by chance check in your renv/library directory into version control? I don't think that's the best way to do it: you probably don't want to check your entire renv into version control, since it won't work for other people using your repository in different operating systems. 

According to the [renv documentation](https://rstudio.github.io/renv/articles/renv.html),

> For development and collaboration, the .Rprofile, renv.lock and renv/activate.R files should be committed to your version control system; the renv/library directory should normally be ignored. Note that [renv::init()](https://rstudio.github.io/renv/reference/init.html) will attempt to write the requisite ignore statements to the project .gitignore.

**Comment by PMassicotte** [comment]
Looking at my renv project directory, there is no `library` folder.

https://github.com/PMassicotte/blog/tree/main/renv

I used `renv::init()`, so these unneeded directories were automatically added to the `.gitignore` file.

https://github.com/PMassicotte/blog/blob/main/renv/.gitignore

**Comment by cscheid** [comment]
Could it be that the issue is that renv is using a stale cache?

```
Moving renv [0.15.5] into the cache ...
	OK [moved to cache in 0.[39](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:42) milliseconds]
Run cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
Run actions/cache@v2
  with:
    path: /home/runner/work/_temp/renv
    key: Ubuntu 20.04.4 LTS-R version 4.2.0 (2022-04-22)-1-72ee58ae62710b72497dc01b87230f47ff7b7b28cacf06d35b68ccbd56c3a16d
    restore-keys: Ubuntu 20.04.4 LTS-R version 4.2.0 (2022-04-22)-1-
  env:
    BUNDLE_EXT: linux-amd64.deb
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RENV_PATHS_ROOT: /home/runner/work/_temp/renv
Received 188743680 of 687912602 (27.4%), 180.0 MBs/sec
Received [40](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:43)6847488 of 687912602 (59.1%), 194.0 MBs/sec
Received 650117120 of 687912602 (94.5%), 206.4 MBs/sec
Received 687912602 of 687912602 (100.0%), 175.2 MBs/sec
Cache Size: ~6[56](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:60) MB (687912602 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/786ae1ac-e6af-40c7-b78e-0a05f8864f5b/cache.tzst -P -C /home/runner/work/blog/blog
Cache restored successfully

Cache restored from key: Ubuntu 20.04.4 LTS-R version 4.2.0 (2022-04-22)-1-ebd9228486baaa294e[59](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:63)dc8ab9d5a[64](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:69)9880901278f0024[67](https://github.com/PMassicotte/blog/runs/7837668229?check_suite_focus=true#step:5:72)2399c489dfd447e0
```

https://github.com/r-lib/actions/tree/v2/setup-renv has instructions on how to handle them

**Comment by PMassicotte** [comment]
Thank you for your answer.

I have tried the instructions here as you pointed out to force rebuilding the cache (i.e. setting `cache-version: 2`).

```yaml
steps:
- uses: actions/checkout@v2
- uses: r-lib/actions/setup-r@v2
- uses: r-lib/actions/setup-renv@v2
  with:
    cache-version: 2
```
It looks like that packages were all reinstalled successfully:

https://github.com/PMassicotte/blog/runs/7845082599?check_suite_focus=true#step:5:1

However, still getting errors when rendering.

https://github.com/PMassicotte/blog/runs/7845082599?check_suite_focus=true#step:6:57

I am a bit confused now :) How the deployment _knows_ that system libraries (such as gdal) should be installed?

**Comment by cscheid** [comment]
Oh - those are _system_ dependencies? Then you just need to use system tools to install them. This is ubuntu, so you'll need to find the right packages and use apt: https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-actions-workflow

**Comment by PMassicotte** [comment]
What I am not understanding is that the R packages install correctly (I am using RSPM, with binaries). It is when the `.qmd` is rendered that the problem appears.

**Comment by cscheid** [comment]
Because those are dynamically linked libraries that are only loaded when code is executed.
