### ISSUE TITLE
Quarto Publish action fails when format: pdf is defined in _quarto.yml

### ISSUE THREAD

**Issue by kbenoit** [quarto-dev/quarto-actions#41]
I followed all of the instructions for setting up the GitHub Action for publishing (with frozen computations) from https://quarto.org/docs/publishing/github-pages.html#github-action. This failed however with the same error reported in #29 (see this [failed run](https://github.com/quanteda/Text-Analysis-Using-R/runs/8009349718?check_suite_focus=true) for instance). I solved it by removing the pdf format from my `_quarto.yml` per the [suggestion](https://github.com/quarto-dev/quarto-actions/issues/29#issuecomment-1211367945) by @clente on that issue.

https://github.com/quanteda/Text-Analysis-Using-R/blob/24b0a189d9a0075ea60ad48b00076ccfa8bc79dd/_quarto.yml#L75-L87

But then in RStudio, the menu option to build the pdf version disappears, which is a shame. It would be nice to retain this option but be able to define the quarto render/publish actions in https://github.com/quarto-dev/quarto-actions/blob/main/publish/action.yml to render HTML only.

Thanks for such an amazing piece of software!! 👏🙏👏

**Comment by cderv** [comment]
Thanks a lot for this report. 

It seems setting the `pdf` format somehow trigger the need for **jsonlite** and some R process. We'll need to look closer into that

**Comment by cderv** [comment]
By the way, the first errors in your actions 
````
Error in loadNamespace(x) : there is no package called ‘jsonlite’
Calls: .main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
WARNING: Unable to perform code-link (code-link requires R packages rmarkdown, downlit, and xml2)
````

are because using `code-link` requires R and some packages, even if you use freeze. This is an unfortunates limitation for now in the way **downlit** is applied.

**Comment by kbenoit** [comment]
Commenting out the `format: pdf: ...` part of _quarto.yml eliminated that error so it seems to be something that is only called when rendering the pdf. Is there a way to edit the GH action script to render the html only, and not everything defined as a format in _quarto.yml?

**Comment by cderv** [comment]
Thanks for the precision, I will look into that then. You have HTML also activated so I thought it was linked. I'll try to reproduce 

>  Is there a way to edit the GH action script to render the html only, and not everything defined as a format in _quarto.yml?

We mention this very briefly in this document : 
https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-04-other-workflows.md#using-quarto-actions-other-workflows

Publish action seems magic because it will render for you... but to all format. This is a simplification we did for v2, and the v1 examples of the action were simplified. 

For a single format, you just need to adopt a two step process: 

* Use the render action to render to you desired format
* Then use the publish action with `render: false` configuration

**Comment by cscheid** [comment]
@cderv Let's figure out a way to make v2 support single formats

**Comment by cderv** [comment]
I see two main ways: 

* `quarto publish` at CLI needs to offer way to pass a format to render instead of just all or nothing
* We could handle this in the publish action by: 
    * Offering a configuration for choosing a format
    * If provided, we run `quarto render` before doing a `quarto publish --no-render`
    * If no provided we run directly the `quarto publish` command

I think the latter would work right ? The former is a bigger change in the CLI, but I can think of some usage were `quarto publish --to html` would be useful to have even if you have a pdf version defined. If you think this is worth tracking, we could have a specific issue for that in Quarto CLI side.

**Comment by cscheid** [comment]
Hm, I misunderstood your earlier message. We _already_ support "render: false". So all we need to do is update the documentation.

**Comment by cscheid** [comment]
Even more to the point, our documentation [already mentions this workflow as well](https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-06-no-render.md). We need to make this more prominent.

**Comment by cscheid** [comment]
I made a number of tweaks to the documentation so we have explicit mentions of single-format rendering now.

**Comment by cderv** [comment]
Ok. So the two step process is indeed the way with the two actions. That is fine ! 

Thanks for the update to the doc

**Comment by kbenoit** [comment]
OK, I redid my publish.yml and _quarto.yml as you suggested above (at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-07-publish-single-format.md). 

It seems to work although I am *still* seeing the jsonlite errors.

* My revised [publish.yml](https://github.com/quanteda/Text-Analysis-Using-R/blob/main/.github/workflows/publish.yml)
* [_quarto.yml](https://github.com/quanteda/Text-Analysis-Using-R/blob/main/_quarto.yml) with pdf turned on again
* Successful build: https://github.com/quanteda/Text-Analysis-Using-R/actions/workflows/publish.yml
* But still seeing jsonlite errors that do not appear to affect the HTML render: https://github.com/quanteda/Text-Analysis-Using-R/runs/8027544320?check_suite_focus=true

**Comment by cscheid** [comment]
This (from your log) looks to me like a bug in our actions. I'll investigate and report back.

```
if [ "html" == "" ]; then
    quarto render .
  else
    quarto render . --to html
fi
if [ -f "_book" ]; then
    echo "QUARTO_OUTPUT=_book" >> $GITHUB_ENV
  elif [ -f "_site"]; then
    echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
fi
```

**Comment by cscheid** [comment]
You still seem to have `code-link: true` in your HTML project, though, right? https://github.com/quanteda/Text-Analysis-Using-R/blob/main/_quarto.yml#L74

`code-link: true` uses R and the `jsonlite` package, like @cderv mentioned above.

**Comment by kbenoit** [comment]
You're right - I disabled code-link and now it builds without error.

There is a warning about a `]` character though that looks like something in the action.
https://github.com/quanteda/Text-Analysis-Using-R/runs/8028121243?check_suite_focus=true#step:4:61

Thanks for all the help!
