### ISSUE TITLE
Quarto action broken?

### ISSUE THREAD

**Issue by juliohm** [quarto-dev/quarto-actions#46]
My GitHub Actions are apparently properly configured, and I can see the green check mark after every commit to master. However, the logs show that the site is being deployed to the wrong URL and the commits to the `gh-pages` branch continuously alternate the URL from

`juliohm.github.io/mysite` (correct)

to

`github.com/juliohm/mysite` (incorrect)

Perhaps this is due to some discrepancy in the version of my local `quarto publish gh-pages` command and the action here?

Can you please help debug this issue further? I am looking forward to seeing my Quarto website published 🙏🏽

**Comment by juliohm** [comment]
Apparently the issue was in the GitHub Pages option in the Settings tab. I had marked GitHub Actions as the option but apparently we have to always use Deploy from Branch and select gh-pages even when we are using the action.

**Comment by cscheid** [comment]
> Ah this helped. Would be super useful to have this somewhere in the guidance. Great job all - so useful to have some examples of different configs.

Pull requests are welcome :) GitHub changes their UI often and it's hard for us to keep up!
