### ISSUE TITLE
set-output deprecated

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-actions#48]
I saw a warning in my CI today:

    Annotations
    1 warning
    build-deploy
    The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Could it be from the following?

https://github.com/quarto-dev/quarto-actions/blob/d1d44ffb885dabd878c341ba7116a603843bb14c/setup/action.yml#L52

**Comment by cscheid** [comment]
Oh yes, that has to be it. I didn't know this had been deprecated. Thanks for the heads up, I'll take a look at fixing it.

**Comment by cscheid** [comment]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cscheid** [comment]
Christophe is not currently available and so his review will take a while, but we should merge it soon. Thanks for the report!

**Comment by fuhrmanator** [comment]
It's not urgent - it's only a warning for now - but one day it will break it seems. I have a lot of actions in my build script and I wasn't 100% sure where the warning was coming from (the warning doesn't give a line number or action context as far as I could see).

**Comment by fuhrmanator** [comment]
@kellyatkinson your screen shot seems to imply a failure of another kind (the red X is that your action halted because of a failure). Can you drill down to the details of why the action failed? 

As far as #49, I don't get that warning anymore with my action.

**Comment by kellyatkinson** [comment]
Thanks @fuhrmanator. I've checked the details and see errors that relate to the deprecated behaviours. I can't understand why these are being generated.
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/8167044/199387977-610e67b0-86f5-4b2b-b0b6-ecd33b65554e.png">

**Comment by fuhrmanator** [comment]
@kellyatkinson when I was getting the warnings, I found an example of an error:
![image](https://user-images.githubusercontent.com/7606540/199398102-f844d2f8-d062-4163-8d3e-93c45f648a83.png)

I had to click on each line with a red X (e.g., **build-deploy**) to drill down (it was two more clicks and some scrolling) and finally in my case it was a LaTeX babel error (surely not the same for you, but hopefully you get the idea of how to find it):

![image](https://user-images.githubusercontent.com/7606540/199398678-05d0eb07-d6f2-4c72-9746-b6314d5f8a5b.png)

**Comment by cscheid** [comment]
It looks like the pdflatex compilation is failing; that points to an issue with quarto itself, and not the actions. Can you please create a github issue over at https://github.com/quarto-dev/quarto-cli and provide the .qmd (or a similar one that causes the same problem)? Thank you!

**Comment by fuhrmanator** [comment]
@cscheid my example above (https://github.com/quarto-dev/quarto-actions/issues/48#issuecomment-1299556759) was to help @kellyatkinson find their problem's details. 

Anyway, the original problem (set-output deprecated) is gone in my case, so I am happy to close this issue.

**Comment by fuhrmanator** [comment]
Today I saw the `set-output deprecated` warning (when I said before the warning was gone, I was looking at the wrong action -- the one that runs to transfer files to GitHub pages). 

Again, I tracked it down to the the `setup` action:

https://github.com/fuhrmanator/log210-ndc-quarto/actions/runs/3401289297/jobs/5656290788#step:4:38
(the instruction is below)

    echo "::set-output name=installer::$(ls quarto*linux-amd64.deb)"

The warning shows at https://github.com/fuhrmanator/log210-ndc-quarto/actions/runs/3401289297/jobs/5656290788#step:4:45

I'm at a loss as to why it's doing this -- is it because the action has to be re-released through the GitHub marketplace or something? The setup action code clearly is different: https://github.com/quarto-dev/quarto-actions/blob/3cf8a3e86821321ff2cdcf6b695f76b2d886946c/setup/action.yml#L52

**Comment by mcanouil** [comment]
For the fix to be available, a new tag/release must be made, in that case it's probably just a patch increment.

**Comment by cscheid** [comment]
@cderv Let's coordinate on this sometime this week or next.

**Comment by cderv** [comment]
@cscheid I did the new release with the fix. Any action using `quarto-dev/quarto-actions@v2` should have the update
