### ISSUE TITLE
Expose installed quarto version "nicely"

### ISSUE THREAD

**Issue by jennybc** [quarto-dev/quarto-actions#52]
It's currently possible to backout what quarto version has gotten installed, but it would be great if the setup action included a call to `quarto --version` or similar so that this is stated cleanly in the log.

**Comment by jennybc** [comment]
Related, I wonder if it should also return this, similar to the `setup-r` action:

https://github.com/r-lib/actions/blob/50d1eae9b8da0bb3f8582c59a5b82225fa2fe7f2/setup-r/action.yml#L53

**Comment by cscheid** [comment]
@jennybc We'll release soon, but there's now a `version` output (assuming I didn't mess anything up!)
