### ISSUE TITLE
Updating extensions using GHA workflow

### ISSUE THREAD

**Issue by IndrajeetPatil** [quarto-dev/quarto-actions#56]
In addition to using the latest Quarto, I would also like to use the latest versions of Quarto extensions. But I can't seem to figure out how to specify this in GHA workflow, and it would be great if you could include an example for this in the current repo.

Here is what I am currently using, but the job to install extensions gets [stuck](https://github.com/IndrajeetPatil/dry-r-package-development/actions/runs/3638947186/jobs/6141748471). 

```yaml
      # The two "Yes" are to answer the following questions:
      #  > Do you trust the authors of this extension(Y/n)?
      #  > Would you like to continue (Y/n)?
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
      - run: |
          echo "Yes" | echo "Yes" | quarto install extension quarto-ext/fontawesome
```

**Comment by cscheid** [comment]
Can you instead create a new action that runs a shell script to install the extension instead?

**Comment by mcanouil** [comment]
I've got no problem installing template or extension in GHA, see <https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/.github/workflows/publish.yml>

To note, the `--no-prompt` option would be the recommended approach.

```
- run: |
    quarto install extension quarto-ext/fontawesome --no-prompt
```

**Comment by IndrajeetPatil** [comment]
> To note, the `--no-prompt` option would be the recommended approach.

Awesome! Thanks, wasn't aware of this option. That definitely [solves](https://github.com/IndrajeetPatil/dry-r-package-development/pull/9) the issue for me.
