### ISSUE TITLE
github action publish broke, invalid value for output-file

### ISSUE THREAD

**Issue by okenk** [quarto-dev/quarto-actions#64]
I have a github action rendering and publishing a quarto book to github pages. It was working for a commit two months ago and now is not. It looks like the book is still rendering, but not publishing. This is the error:
`In file /home/runner/work/pfmc_assessment_handbook/pfmc_assessment_handbook/index.qmd
  Invalid value for output-file: paths are not allowed`

It goes on to list a number of invalid file paths for output-file. I am not sure how to create a minimally reproducible example, but the error is [here](https://github.com/pfmc-assessments/pfmc_assessment_handbook/actions/runs/3971569631/jobs/6808613165#step:13:65).

Thank you!

**Comment by dragonstyle** [comment]
This looks to be a regression caused by work on our book support. I'm looking at it now- thank you for reporting it!

**Comment by dragonstyle** [comment]
Actually correction -this issue is actually related to the title of the document:

`Unofficial NWFSC/SWFSC Groundfish Stock Assessment Handbook` - the `/` character is being interpreted as a path. I'm taking a look now...

**Comment by dragonstyle** [comment]
Ok this should be fixed in our next prerelease build which should be available shortly.

**Comment by okenk** [comment]
Awesome, thank you so much, it is working now.
