### ISSUE TITLE
Quarto Publish GH Action fails with `ERROR: No previous publishes available to re-publish (previous publish required with --no-prompt)`

### ISSUE THREAD

**Issue by Sparrow0hawk** [quarto-dev/quarto-actions#67]
I've been trying to setup the GitHub action `quarto-dev/quarto-actions/publish@v2` on [my repo for Quarto slides](https://github.com/Sparrow0hawk/quarto-slides).

Whenever I push it fails with [[example](https://github.com/Sparrow0hawk/quarto-slides/actions/runs/4055292849/jobs/6978230078)] :
```
ERROR: No previous publishes available to re-publish (previous publish required with --no-prompt)
```

I initially thought this was because i'd committed the GitHub action before running `quarto publish gh-pages` locally but after deleting the GitHub repository, pushing the code back, cancelling the GH action run and running `quarto publish gh-pages` I still get this error.

Running `quarto publish gh-pages --no-prompt` locally does not solve this issue.

**Comment by cscheid** [comment]
You're running a very old version of quarto: https://github.com/Sparrow0hawk/quarto-slides/blob/main/.github/workflows/quarto-publish.yml#L20

Can you try running a newer version?

**Comment by Sparrow0hawk** [comment]
Thanks, i've changed it to 1.2.335 and now get a permissions error ([Action log](https://github.com/Sparrow0hawk/quarto-slides/actions/runs/4068019956/jobs/7007216021).

```bash
origin	https://github.com/Sparrow0hawk/quarto-slides (fetch)
origin	https://github.com/Sparrow0hawk/quarto-slides (push)
remote: Permission to Sparrow0hawk/quarto-slides.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Sparrow0hawk/quarto-slides/': The requested URL returned error: 403
```

I've gone into the repo settings >Actions > Workflow permissions and changed this to "Read and write permissions" and rerunning has worked!

**Comment by Sparrow0hawk** [comment]
I got to this initial error by copy and [pasting this example](https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml) and just uncommenting the lines there.

I've submitted a small PR adjusting the commented out version line incase anyone repeats my mistake #68

**Comment by cscheid** [comment]
I was wondering where that old version came from, and you're 100% correct that this is a problem. Merged the PR, and will go ahead and close this. Thank you for the feedback!
