### ISSUE TITLE
quarto-dev/quarto-actions/publish@v2 is clobbering my CNAME in gh-pages branch

### ISSUE THREAD

**Issue by andrewcstewart** [quarto-dev/quarto-actions#73]
Recently each time I run quarto-dev/quarto-actions/publish@v2 my custom domain for my gh-pages deployment gets clobbered.  Looking in the gha log I spot the following:

```
delete mode 100644 CNAME
```

Not sure if there's already a mechanism to tell the action to not delete that file, but it might be a good idea to include an option like https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-add-cname-file-cname

**Comment by cderv** [comment]
FWIW this was also mentioned and discussed in https://github.com/quarto-dev/quarto-cli/discussions/3249

**Comment by allenmanning** [comment]
> FWIW this was also mentioned and discussed in [quarto-dev/quarto-cli#3249](https://github.com/quarto-dev/quarto-cli/discussions/3249)

Is this a duplicate?

**Comment by cderv** [comment]
> Is this a duplicate?

Yes probably. One is a discussion item, and this one is an issue.  However, I believe the solution given in the discussion is the one to follow.

**Comment by cderv** [comment]
@andrewcstewart does the solution provided works ok for you ? 

Thank you

**Comment by andrewcstewart** [comment]
Doh, why didn't I think of that?  Yes that would work fine.
