### ISSUE TITLE
publish: How to achieve `quarto publish gh-pages --no-browser`?

### ISSUE THREAD

**Issue by HenrikBengtsson** [quarto-dev/quarto-actions#76]
With a _private_ GitHub repository and public GitHub Pages, you can publish at the command line using:

```sh
quarto publish gh-pages --no-browser
```

cf. <https://quarto.org/docs/publishing/github-pages.html#private-sites>.

Is it possible get that `--no-browser` argument with `quarto-dev/quarto-actions/publish@v2`?

**Comment by cscheid** [comment]
Good point. It feels like we should always pass this option, right @cderv? I don't see a downside since we're in CI...

**Comment by cderv** [comment]
Yes I think we can add that to the action no matter if private or public. 

We could also allow passing any flag for avoid this constraint in the future. But one can run `quarto publish` directly in this case I guess.

**Comment by Robinlovelace** [comment]
Just to add, I think this caused a crash in my workflow: ERROR: Unknown option "--no-browser". Did you mean option "--version"?

Source: https://github.com/nptscot/networkmerge/actions/runs/7071037924/job/19248315056#step:6:44

I've tried updating to a later version of Quarto here: https://github.com/nptscot/networkmerge/pull/66/commits/8b198abad6529ac0d86983add1ac0a363a298e9d

That should fix it, right?

**Comment by Robinlovelace** [comment]
Cause: very out of date version in examples. Patch submitted as PR: https://github.com/quarto-dev/quarto-actions/pull/93
