### ISSUE TITLE
`output-dir`not recoginzed by publish action

### ISSUE THREAD

**Issue by SilasK** [quarto-dev/quarto-actions#88]
In my base folder/_quarto.yml
I have specified:
```
output-dir: output
```

This renders my document in 

`writing/manuscript.qmd` to `output/writing/manuscript.html`

But then I get an error in the github action.

Run quarto-dev/quarto-actions/publish@v2
Run git config --global user.email "quarto-github-actions-publish@example.com"
From https://github.com/trajkovski-lab/Subspecies_manuscript
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
ERROR: Output file manuscript.html does not exist.

**Comment by cderv** [comment]
I believe this is related to this issue in Quarto 
* https://github.com/quarto-dev/quarto-cli/issues/5220

**Comment by SilasK** [comment]
True.
