### ISSUE TITLE
Test on multiple versions including prerelease

### ISSUE THREAD

**Issue by pat-alt** [quarto-dev/quarto-actions#92]
Hi there, 

I've set up basic [workflows](https://github.com/pat-alt/quarto-juliacon-proceedings/blob/main/.github/workflows/render.yml) for a Quarto [extension](https://github.com/pat-alt/quarto-juliacon-proceedings) I'm working on. 

Is it possible to test on multiple version including prerelease? 

Thanks!

**Comment by cderv** [comment]
This is just a Github Action thing. You can definitely do a Matrix on the quarto version that you can specific when you install quarto with the actions: 

See version field at  https://github.com/quarto-dev/quarto-actions/tree/main/setup#inputs-available


And look for how to setup a strategy matrix to test with Github action under different scenario

**Comment by pat-alt** [comment]
Perfect, thanks @cderv
